import { Theme, themeSchema, Tokens } from './theme';
export function makeTheme(
  name: string,
  description: string,
  primary: string,
  accent: string,
  heading: Theme['typography']['heading'] = 'Inter',
): Theme {
  const light: Tokens = {
    background: '#f5f7fa',
    foreground: '#172a3a',
    card: '#ffffff',
    cardForeground: '#172a3a',
    primary,
    primaryForeground: '#ffffff',
    secondary: '#e8edf2',
    secondaryForeground: '#263746',
    accent,
    accentForeground: '#172a3a',
    muted: '#eef2f6',
    mutedForeground: '#5d6b7a',
    border: '#dce3eb',
    input: '#dce3eb',
    ring: primary,
    destructive: '#bd2f37',
    destructiveForeground: '#ffffff',
    success: '#19734b',
    warning: '#996000',
    info: '#2563a8',
  };
  const dark: Tokens = {
    background: '#101923',
    foreground: '#edf2f7',
    card: '#192633',
    cardForeground: '#edf2f7',
    primary: accent,
    primaryForeground: '#101923',
    secondary: '#2a3947',
    secondaryForeground: '#edf2f7',
    accent: '#adc7e2',
    accentForeground: '#101923',
    muted: '#233240',
    mutedForeground: '#b2becc',
    border: '#3b4b5d',
    input: '#3b4b5d',
    ring: accent,
    destructive: '#fa7c85',
    destructiveForeground: '#101923',
    success: '#70d4a6',
    warning: '#f2c36b',
    info: '#8fc4ff',
  };
  return themeSchema.parse({
    name,
    description,
    mood: ['considered', 'modern', 'trustworthy'],
    light,
    dark,
    typography: { heading, body: 'Inter' },
    radius: '0.75rem',
    shadows: {
      soft: '0 2px 6px rgba(16,30,50,0.04)',
      medium: '0 8px 24px rgba(16,30,50,0.08)',
      strong: '0 16px 48px rgba(16,30,50,0.14)',
    },
    accessibilityNotes:
      'Check contrast after editing. Status colors need text or icons, not color alone.',
    explanation:
      'A grounded primary anchors actions while a lighter accent provides emphasis. Independent dark tokens preserve hierarchy.',
  });
}
export const presets: Theme[] = [
  makeTheme('Modern SaaS', 'Clear interfaces for ambitious products.', '#3155b7', '#a9c4ff'),
  makeTheme(
    'Premium Travel',
    'Warm discovery meets dependable blue.',
    '#174e65',
    '#e9c46a',
    'Georgia',
  ),
  makeTheme(
    'Luxury Ecommerce',
    'Quiet confidence, elevated essentials.',
    '#353e34',
    '#d4c3a0',
    'Georgia',
  ),
  makeTheme('Minimal Portfolio', 'Let your work speak for itself.', '#303a46', '#c4d1dc'),
  makeTheme('Finance Dashboard', 'Precise data with a confident teal.', '#11645f', '#93ded0'),
  makeTheme(
    'Education Platform',
    'An inviting place to learn and grow.',
    '#a14523',
    '#f5c38d',
    'Trebuchet MS',
  ),
  makeTheme(
    'Dark Developer Tool',
    'Focused tools for deep work.',
    '#5144a6',
    '#b8acf5',
    'Courier New',
  ),
];
